package com.indra.checkmynationality;

import java.util.HashMap;

public class CountryMap {
    private HashMap<String, String> countryCodes = new HashMap<>();

    public void setCountryCodes() {
        countryCodes.put("AD", "Andorra, Principality Of");
        countryCodes.put("AE", "United Arab Emirates");
        countryCodes.put("AF", "Afghanistan, Islamic State Of");
        countryCodes.put("AG", "Antigua And Barbuda");
        countryCodes.put("AI", "Anguilla");
        countryCodes.put("AL", "Albania");
        countryCodes.put("AM", "Armenia");
        countryCodes.put("AN", "Netherlands Antilles");
        countryCodes.put("AO", "Angola");
        countryCodes.put("AQ", "Antarctica");
        countryCodes.put("AR", "Argentina");
        countryCodes.put("AS", "American Samoa");
        countryCodes.put("AT", "Austria");
        countryCodes.put("AU", "Australia");
        countryCodes.put("AW", "Aruba");
        countryCodes.put("AZ", "Azerbaidjan");
        countryCodes.put("BA", "Bosnia-Herzegovina");
        countryCodes.put("BB", "Barbados");
        countryCodes.put("BD", "Bangladesh");
        countryCodes.put("BE", "Belgium");
        countryCodes.put("BF", "Burkina Faso");
        countryCodes.put("BG", "Bulgaria");
        countryCodes.put("BH", "Bahrain");
        countryCodes.put("BI", "Burundi");
        countryCodes.put("BJ", "Benin");
        countryCodes.put("BM", "Bermuda");
        countryCodes.put("BN", "Brunei Darussalam");
        countryCodes.put("BO", "Bolivia");
        countryCodes.put("BR", "Brazil");
        countryCodes.put("BS", "Bahamas");
        countryCodes.put("BT", "Bhutan");
        countryCodes.put("BV", "Bouvet Island");
        countryCodes.put("BW", "Botswana");
        countryCodes.put("BY", "Belarus");
        countryCodes.put("BZ", "Belize");
        countryCodes.put("CA", "Canada");
        countryCodes.put("CC", "Cocos (Keeling) Islands");
        countryCodes.put("CF", "Central African Republic");
        countryCodes.put("CD", "Congo, The Democratic Republic Of The");
        countryCodes.put("CG", "Congo");
        countryCodes.put("CH", "Switzerland");
        countryCodes.put("CI", "Ivory Coast (Cote D'Ivoire)");
        countryCodes.put("CK", "Cook Islands");
        countryCodes.put("CL", "Chile");
        countryCodes.put("CM", "Cameroon");
        countryCodes.put("CN", "China");
        countryCodes.put("CO", "Colombia");
        countryCodes.put("CR", "Costa Rica");
        countryCodes.put("CS", "Former Czechoslovakia");
        countryCodes.put("CU", "Cuba");
        countryCodes.put("CV", "Cape Verde");
        countryCodes.put("CX", "Christmas Island");
        countryCodes.put("CY", "Cyprus");
        countryCodes.put("CZ", "Czech Republic");
        countryCodes.put("DE", "Germany");
        countryCodes.put("DJ", "Djibouti");
        countryCodes.put("DK", "Denmark");
        countryCodes.put("DM", "Dominica");
        countryCodes.put("DO", "Dominican Republic");
        countryCodes.put("DZ", "Algeria");
        countryCodes.put("EC", "Ecuador");
        countryCodes.put("EE", "Estonia");
        countryCodes.put("EG", "Egypt");
        countryCodes.put("EH", "Western Sahara");
        countryCodes.put("ER", "Eritrea");
        countryCodes.put("ES", "Spain");
        countryCodes.put("ET", "Ethiopia");
        countryCodes.put("FI", "Finland");
        countryCodes.put("FJ", "Fiji");
        countryCodes.put("FK", "Falkland Islands");
        countryCodes.put("FM", "Micronesia");
        countryCodes.put("FO", "Faroe Islands");
        countryCodes.put("FR", "France");
        countryCodes.put("FX", "France (European Territory)");
        countryCodes.put("GA", "Gabon");
        countryCodes.put("UK", "Great Britain");
        countryCodes.put("GD", "Grenada");
        countryCodes.put("GE", "Georgia");
        countryCodes.put("GF", "French Guyana");
        countryCodes.put("GH", "Ghana");
        countryCodes.put("GI", "Gibraltar");
        countryCodes.put("GL", "Greenland");
        countryCodes.put("GM", "Gambia");
        countryCodes.put("GN", "Guinea");
        countryCodes.put("GP", "Guadeloupe (French)");
        countryCodes.put("GQ", "Equatorial Guinea");
        countryCodes.put("GR", "Greece");
        countryCodes.put("GS", "S. Georgia & S. Sandwich Isls.");
        countryCodes.put("GT", "Guatemala");
        countryCodes.put("GU", "Guam (USA)");
        countryCodes.put("GW", "Guinea Bissau");
        countryCodes.put("GY", "Guyana");
        countryCodes.put("HK", "Hong Kong");
        countryCodes.put("HM", "Heard And McDonald Islands");
        countryCodes.put("HN", "Honduras");
        countryCodes.put("HR", "Croatia");
        countryCodes.put("HT", "Haiti");
        countryCodes.put("HU", "Hungary");
        countryCodes.put("ID", "Indonesia");
        countryCodes.put("IE", "Ireland");
        countryCodes.put("IL", "Israel");
        countryCodes.put("IN", "India");
        countryCodes.put("IO", "British Indian Ocean Territory");
        countryCodes.put("IQ", "Iraq");
        countryCodes.put("IR", "Iran");
        countryCodes.put("IS", "Iceland");
        countryCodes.put("IT", "Italy");
        countryCodes.put("JM", "Jamaica");
        countryCodes.put("JO", "Jordan");
        countryCodes.put("JP", "Japan");
        countryCodes.put("KE", "Kenya");
        countryCodes.put("KG", "Kyrgyz Republic (Kyrgyzstan)");
        countryCodes.put("KH", "Cambodia, Kingdom Of");
        countryCodes.put("KI", "Kiribati");
        countryCodes.put("KM", "Comoros");
        countryCodes.put("KN", "Saint Kitts & Nevis Anguilla");
        countryCodes.put("KP", "North Korea");
        countryCodes.put("KR", "South Korea");
        countryCodes.put("KW", "Kuwait");
        countryCodes.put("KY", "Cayman Islands");
        countryCodes.put("KZ", "Kazakhstan");
        countryCodes.put("LA", "Laos");
        countryCodes.put("LB", "Lebanon");
        countryCodes.put("LC", "Saint Lucia");
        countryCodes.put("LI", "Liechtenstein");
        countryCodes.put("LK", "Sri Lanka");
        countryCodes.put("LR", "Liberia");
        countryCodes.put("LS", "Lesotho");
        countryCodes.put("LT", "Lithuania");
        countryCodes.put("LU", "Luxembourg");
        countryCodes.put("LV", "Latvia");
        countryCodes.put("LY", "Libya");
        countryCodes.put("MA", "Morocco");
        countryCodes.put("MC", "Monaco");
        countryCodes.put("MD", "Moldavia");
        countryCodes.put("MG", "Madagascar");
        countryCodes.put("MH", "Marshall Islands");
        countryCodes.put("MK", "Macedonia");
        countryCodes.put("ML", "Mali");
        countryCodes.put("MM", "Myanmar");
        countryCodes.put("MN", "Mongolia");
        countryCodes.put("MO", "Macau");
        countryCodes.put("MP", "Northern Mariana Islands");
        countryCodes.put("MQ", "Martinique (French)");
        countryCodes.put("MR", "Mauritania");
        countryCodes.put("MS", "Montserrat");
        countryCodes.put("MT", "Malta");
        countryCodes.put("MU", "Mauritius");
        countryCodes.put("MV", "Maldives");
        countryCodes.put("MW", "Malawi");
        countryCodes.put("MX", "Mexico");
        countryCodes.put("MY", "Malaysia");
        countryCodes.put("MZ", "Mozambique");
        countryCodes.put("NA", "Namibia");
        countryCodes.put("NC", "New Caledonia (French)");
        countryCodes.put("NE", "Niger");
        countryCodes.put("NF", "Norfolk Island");
        countryCodes.put("NG", "Nigeria");
        countryCodes.put("NI", "Nicaragua");
        countryCodes.put("NL", "Netherlands");
        countryCodes.put("NO", "Norway");
        countryCodes.put("NP", "Nepal");
        countryCodes.put("NR", "Nauru");
        countryCodes.put("NT", "Neutral Zone");
        countryCodes.put("NU", "Niue");
        countryCodes.put("NZ", "New Zealand");
        countryCodes.put("OM", "Oman");
        countryCodes.put("PA", "Panama");
        countryCodes.put("PE", "Peru");
        countryCodes.put("PF", "Polynesia (French)");
        countryCodes.put("PG", "Papua New Guinea");
        countryCodes.put("PH", "Philippines");
        countryCodes.put("PK", "Pakistan");
        countryCodes.put("PL", "Poland");
        countryCodes.put("PM", "Saint Pierre And Miquelon");
        countryCodes.put("PN", "Pitcairn Island");
        countryCodes.put("PR", "Puerto Rico");
        countryCodes.put("PT", "Portugal");
        countryCodes.put("PW", "Palau");
        countryCodes.put("PY", "Paraguay");
        countryCodes.put("QA", "Qatar");
        countryCodes.put("RE", "Reunion (French)");
        countryCodes.put("RO", "Romania");
        countryCodes.put("RU", "Russian Federation");
        countryCodes.put("RW", "Rwanda");
        countryCodes.put("SA", "Saudi Arabia");
        countryCodes.put("SB", "Solomon Islands");
        countryCodes.put("SC", "Seychelles");
        countryCodes.put("SD", "Sudan");
        countryCodes.put("SE", "Sweden");
        countryCodes.put("SG", "Singapore");
        countryCodes.put("SH", "Saint Helena");
        countryCodes.put("SI", "Slovenia");
        countryCodes.put("SJ", "Svalbard And Jan Mayen Islands");
        countryCodes.put("SK", "Slovak Republic");
        countryCodes.put("SL", "Sierra Leone");
        countryCodes.put("SM", "San Marino");
        countryCodes.put("SN", "Senegal");
        countryCodes.put("SO", "Somalia");
        countryCodes.put("SR", "Suriname");
        countryCodes.put("ST", "Saint Tome (Sao Tome) And Principe");
        countryCodes.put("SU", "Former USSR");
        countryCodes.put("SV", "El Salvador");
        countryCodes.put("SY", "Syria");
        countryCodes.put("SZ", "Swaziland");
        countryCodes.put("TC", "Turks And Caicos Islands");
        countryCodes.put("TD", "Chad");
        countryCodes.put("TF", "French Southern Territories");
        countryCodes.put("TG", "Togo");
        countryCodes.put("TH", "Thailand");
        countryCodes.put("TJ", "Tadjikistan");
        countryCodes.put("TK", "Tokelau");
        countryCodes.put("TM", "Turkmenistan");
        countryCodes.put("TN", "Tunisia");
        countryCodes.put("TO", "Tonga");
        countryCodes.put("TP", "East Timor");
        countryCodes.put("TR", "Turkey");
        countryCodes.put("TT", "Trinidad And Tobago");
        countryCodes.put("TV", "Tuvalu");
        countryCodes.put("TW", "Taiwan");
        countryCodes.put("TZ", "Tanzania");
        countryCodes.put("UA", "Ukraine");
        countryCodes.put("UG", "Uganda");
        countryCodes.put("UM", "USA Minor Outlying Islands");
        countryCodes.put("US", "United States");
        countryCodes.put("UY", "Uruguay");
        countryCodes.put("UZ", "Uzbekistan");
        countryCodes.put("VA", "Holy See (Vatican City State)");
        countryCodes.put("VC", "Saint Vincent & Grenadines");
        countryCodes.put("VE", "Venezuela");
        countryCodes.put("VG", "Virgin Islands (British)");
        countryCodes.put("VI", "Virgin Islands (USA)");
        countryCodes.put("VN", "Vietnam");
        countryCodes.put("VU", "Vanuatu");
        countryCodes.put("WF", "Wallis And Futuna Islands");
        countryCodes.put("WS", "Samoa");
        countryCodes.put("YE", "Yemen");
        countryCodes.put("YT", "Mayotte");
        countryCodes.put("YU", "Yugoslavia");
        countryCodes.put("ZA", "South Africa");
        countryCodes.put("ZM", "Zambia");
        countryCodes.put("ZR", "Zaire");
        countryCodes.put("ZW", "Zimbabwe");
    }

    public String getCountryName(String s) {
        return countryCodes.get(s);
    }
}
